version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./docker/php
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306

  composer:
    build: ./docker/composer
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  node:
    image: node:11-alpine
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work
    tty: true

  laravel-echo-server:
    build: ./docker/laravel-echo-server
    ports:
      - ${LARAVEL_ECHO_PORT}:6001

  redis:
    image: redis:alpine

  php-worker:
    build: ./docker/php-worker
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - composer

volumes:
  db-data:
    driver: local
